### ISSUE TITLE
How to run the code with my own images?

### ISSUE THREAD

**Issue by viniciosgnr** [nyukat/GMIC#12]
How to run the code with my own images?

**Comment by seyiqi** [comment]
Hi,

You can do so by:
1. replacing the images in https://github.com/nyukat/GMIC/tree/master/sample_data/images. The model expects images with size 2944*1920. 
2. Creating your own data list pickle file such as the one in https://github.com/nyukat/GMIC/blob/master/sample_data/exam_list_before_cropping.pkl
3. Follow the pipeline in https://github.com/nyukat/GMIC/blob/master/example_notebook.ipynb.
