### ISSUE TITLE
RetrieveROIModule on left border and mask not updated for some images

### ISSUE THREAD

**Issue by jamesjjcondon** [nyukat/GMIC#13]
Hey, 

see visualisation for 0_R-MLO.png
![image](https://user-images.githubusercontent.com/33615047/108005245-1bb90a80-7048-11eb-89f1-fe60673a5463.png)

This occurs for only some ROIs eg 0_L-MLO.png:
![image](https://user-images.githubusercontent.com/33615047/108004990-5e2e1780-7047-11eb-9a84-002d306d52de.png)

I'm exploring around [here](https://github.com/nyukat/GMIC/blob/261c2f0f5201e6f8d8803ee6ffb8fa3f348584cd/src/modeling/modules.py#L361) but any pointers would be much appreciated. 

Also, the max value approach will be counfounded by markers, and probably perform poorly for women with very dense breasts eg:
![image](https://user-images.githubusercontent.com/33615047/108005094-a5b4a380-7047-11eb-846e-eadd9fb8e4db.png)

In my case, all patches can't get past x=0 (stuck on the left border).

Is this just me?

**Comment by seyiqi** [comment]
Hi @jamesjjcondon ,

What's the PyTorch version that you are using? Here is the results for 0_R-MLO.png I obtained with PyTorch 1.1.0:
![0_R-MLO](https://user-images.githubusercontent.com/6496413/108006586-e1a92380-6fc9-11eb-93d4-9a2098b22e76.png)


It seems to me that the patch selection logic does not behave as it's expected in your environment. For instance, in your 0_R-MLO.png, while the benign lesion in the lower breast is highlighted by the saliency map, the patch selection module does not select any patch on the highlighted regions.

A.S.

**Comment by jamesjjcondon** [comment]
Thanks for that, 

Struggling with dependencies. What python version are you using? are you using virtualenv? Are you able to remake a fresh environment? Depending on the python version, I'm having trouble with deprecations on Ubuntu 20.04.

**Comment by seyiqi** [comment]
This is the OS info that we primarily run experients on:
Operating System: Red Hat Enterprise Linux
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
            Kernel: Linux 4.14.0-115.33.1.el7a.ppc64le
      Architecture: ppc64-le

I think both Python 3.6.x and 3.7.x should work. I believe the main reason is PyTorch version. If you have an empty env, then pip install -r requirements.txt should do the work.

**Comment by jamesjjcondon** [comment]
Thanks @seyiqi . There are some sym link issues with virtualenv on ubuntu 20.04 and using `sudo` defaults to python3.8. Works with torch 1.1.0.

**Comment by Ch1kara** [comment]
I think the reason we always get x=0 is due to the following code in 'scr/utilities/tools.py',
max_idx_x = max_linear_idx / W_map
max_idx_y = max_linear_idx - max_idx_x * W_map
max_idx_y here will always output 0

**Comment by jamesjjcondon** [comment]
max_idx_x = max_idx_x.type(torch.long) # max_idx_x is float in torch 1.8

Needs to go in  above line 199 in tools.get_max_window for torch 1.8

**Comment by Ch1kara** [comment]
But max_idx_y is still zero in this case since max_idx_y = max_linear_idx - max_linear_idx, not sure if I miss something.
