### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by Ch1kara** [nyukat/GMIC#16]
Hi there,

Thanks for sharing the code. I have a question in terms of the training part.
Given that the GMIC can be trained end-to-end, so the f_g and f_l would be updated simultaneously during training. But, at the early stage, the saliency maps could make mistake and cause the retrieve_roi function to extract incorrect patches (i.e., background), would that affect the convergence of the local module?

Cheers

**Comment by seyiqi** [comment]
Hi @Ch1kara ,

Yes, when the global module is weak in localizing true ROI, the local module might learn from possibly incorrect patches. In our experiment, we found that as long as the global module can provide non-trivial localization, the local module will eventually learn to classify using noisy patch sets that contain irrelevant inforamtion. Hope this helps.

Best,
