### ISSUE TITLE
GMIC- Segmentation

### ISSUE THREAD

**Issue by Andy-git-2021** [nyukat/GMIC#18]
Hello, I`m testing the results from the code for new images in a federal brazilian hospital. When i download the samples from git, it comes already cropped at sample images folder and besides that it looks like has a modification on histograms. Is this an error, the images wouldn´t come without cropping? Because new pacient´s samples images that could be introduced in the same place that is in the sample images folder comes with segmentation folder include before running the code. And when it replaced with new images for run the code again, the folder segmentation, not appear for the new sample images from my own.
Thanks for your attention,

Andressa.

**Comment by seyiqi** [comment]
Hi @Andy-git-2021 ,

Thanks for using our model. 

1. "It comes already cropped at sample images folder and besides that it looks like has a modification on histograms."  **In fact, those are the images that we retrieved from the DICOM file. The visual impression by viewing these images on git may indicate that it's histogram-adjusted. But the reason why the images might look weird is that each pixel value is not in the range [0, 255] but rather [0, 2^16]. This is value setting is given by DICOM protocol.**
2.  "And when it replaced with new images for run the code again, the folder segmentation, not appear for the new sample images from my own." **When you run the code again, preprocessed images will be saved to CROPPED_IMAGE_PATH defined in run.sh. If you don't want to override the images between each run, you need to modify the data_list file specified in INITIAL_EXAM_LIST_PATH. Specifically, images in the different exams should have different names.**

**Comment by kjgeras** [comment]
@Andy-git-2021 please shoot me at email at k.j.geras@nyu.edu. We are working on a project that you might be interested in collaborating with us on.
