### ISSUE TITLE
The reason set the classification as a 2 class multi-label problem

### ISSUE THREAD

**Issue by emma-sjwang** [nyukat/GMIC#20]
Hi, thank you very much for your sharing.
I am newer to mammography classification.
I have read several papers but some of them treat this problem as 2-class classification problem.
May I know the reason why this paper utilizing multi-label to deal with this problem?

Thank you very much.

**Comment by seyiqi** [comment]
Hi @emma-sjwang,

We formulated the problem as a multi-label one because we extracted benign labels along with the malignant labels from the pathology reports in our private dataset. It's not a decision based on technical reasons.
