### ISSUE TITLE
Tool for running the code

### ISSUE THREAD

**Issue by zeeno95** [nyukat/GMIC#22]
I want to reproduce the results of your paper. I have used the google colab but there are lots of issues. Can you plz assist me with which tool you have used for implementation?

**Comment by kjgeras** [comment]
@zeeno95 you have to ask much more specific questions if you expect us to be able to help.

**Comment by kjgeras** [comment]
Please check this out: https://github.com/nyukat/mammography_metarepository.
It might be an answer to your problems.
