### ISSUE TITLE
Potential issue in patch map display

### ISSUE THREAD

**Issue by taijizhao** [nyukat/GMIC#23]
First congratulations for the great project!
I tried to run the run.sh file with the  --visualization-flag on, the resulting patch maps were always aligned to the left border of the image and do not correspond to the activated regions in the heat maps. 
![image](https://user-images.githubusercontent.com/7842342/154221956-6f0ee1e5-928b-4c2c-b53d-a0ca02af11f8.png)

![image](https://user-images.githubusercontent.com/7842342/154222119-9abc4ef5-3d85-42af-87b4-b16e7f366d53.png)

![image](https://user-images.githubusercontent.com/7842342/154222447-332acfb6-9890-46be-8cda-341f59f322ff.png)

I haven't figured out if this is a problem only in the visualization or it also affects the prediction accuracy. 
Thank you very much!

**Comment by taijizhao** [comment]
Moreover, when I use MODEL_INDEX='4' to run the inference, it returns the following error:
`Stage 1: Crop Mammograms
Error: the directory to save cropped images already exists.
Stage 2: Extract Centers
Stage 3: Run Classifier
  0%|                                                                                                                                          | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "src/scripts/run_model.py", line 302, in <module>
    main()
  File "src/scripts/run_model.py", line 292, in main
    start_experiment(
  File "src/scripts/run_model.py", line 255, in start_experiment
    output_df = run_single_model(single_model_path, data_path, parameters, turn_on_visualization)
  File "src/scripts/run_model.py", line 220, in run_single_model
    output_df = run_model(model, exam_list, parameters, turn_on_visualization)
  File "src/scripts/run_model.py", line 183, in run_model
    output = model(tensor_batch)
  File "/home/zhao/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/zhao/HD1/work_zhao/GMIC-master/src/modeling/gmic.py", line 126, in forward
    self.patch_locations = self._convert_crop_position(small_x_locations, self.cam_size, x_original)
  File "/media/zhao/HD1/work_zhao/GMIC-master/src/modeling/gmic.py", line 80, in _convert_crop_position
    assert np.min(top_k_prop_y) >= 0.0, "top_k_prop_y <= 0.0"
AssertionError: top_k_prop_y <= 0.0
`

**Comment by seyiqi** [comment]
Hi @taijizhao ,

I am glad this repo is helpful to you. The cause is probably the torch version. This script was developed under torch 1.1.0. Please see this post for more info: https://github.com/nyukat/GMIC/issues/13

Best,

**Comment by taijizhao** [comment]
> Hi @taijizhao ,
> 
> I am glad this repo is helpful to you. The cause is probably the torch version. This script was developed under torch 1.1.0. Please see this post for more info: #13
> 
> Best,

Thank you very much!
I should have checked previous posts more carefully.
