### ISSUE TITLE
How to run GMIC on CBIS-DDSM?

### ISSUE THREAD

**Issue by HongjianLi** [nyukat/GMIC#25]
Hi. I want to use GMIC to predict the benign/malignant label of CBIS-DDSM images. This repository provides five models pretrained on NYUBCS, and a run.sh script. To predict, I simply replaced the four NYUBCS samples (16 images) in sample_data/images/ by four CBIS-DDSM samples, and then executed run.sh. However, the sample_output/predictions.csv gave small probability values, mostly < 0.1. Therefore it is hard to tell benign/malignant. Which part went wrong?

I read the paper, which mentions "To preprocess mammography images in CBIS-DDSM, we first found the largest connected component containing only non-zero pixels to locate the breast. We then applied erosion and dilation to refine the breast margin. Lastly, we re-oriented all mammography images so that the breasts are always on the left side of the image. All images are resized to 2944 × 1920 pixels and pixels values were normalized to the range [0,1]."    Obviously there were some preprocessing steps. Are these preprocessing steps included in run.sh? If not, where to obtain the code or how to implement these steps?

Thank you.

**Comment by kjgeras** [comment]
Please check this repository: https://github.com/nyukat/mammography_metarepository
