### ISSUE TITLE
Any chance we could invite you guys to Kaggle comp?

### ISSUE THREAD

**Issue by blazespinnaker** [nyukat/GMIC#28]
Your models are great!   Having you folks join in, even if just to give some encouragement and hints would be really fantastic.

https://www.kaggle.com/competitions/rsna-breast-cancer-detection/discussion/372673

If you can spread the word in the community that'd be helpful as well.

**Comment by kjgeras** [comment]
Hi @blazespinnaker,

We are focused too much on other things at the moment to take part in this competition, but it's pretty obvious that using our model as a starting point for pretraining is a good idea. 

You should also check out our earlier work: https://github.com/nyukat/breast_cancer_classifier.

**Comment by blazespinnaker** [comment]
Cheers.   We'd love to use your model, however your license is rather restrictive  (not that there is anything wrong with that! =) .   Would it be possible to get a waiver of sorts?
