### ISSUE TITLE
Missing parameter?

### ISSUE THREAD

**Issue by DrJohnCa** [nyukat/GMIC#29]
When loading models I get:

```
_IncompatibleKeys(missing_keys=[], unexpected_keys=['shared_rep_filter.weight'])
```

It looks like a 256x256x4x4 (4x4 conv?) weight but not implemented in the repo. Any chance this can be added?

**Comment by seyiqi** [comment]
Hi @DrJohnCa ,

Indeed, shared_rep_filter is a parameter that is not used in the GMIC. Some weight files might contain it. However, when loading the weight, if you set strict=False in the [module.load_state_dict](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=load_state_dict#torch.nn.Module.load_state_dict) function as exemplified [in this line](https://github.com/nyukat/GMIC/blob/master/src/scripts/run_model.py#L214) in the run_mode.py script, the problem should be resolved. 

Let me know if you have any other questions.

Best,
Artie
