### ISSUE TITLE
without segmentation path

### ISSUE THREAD

**Issue by ankitdata** [nyukat/GMIC#6]
hi,

How i can run the model without segmentation path and segmentation folder inside sample_data
I have cropped images and i want visualization only.
Is it possible ?

**Comment by seyiqi** [comment]
Yes. You can do so by replacing the benign_seg and malignant_seg in this line: https://github.com/nyukat/GMIC/blob/master/src/scripts/run_model.py#L191
with zero matrices that are exactly the same shapes with your input images.
